config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for  :users,
              :path => '',
              # shortcut for routs e.g. /users/sign_in = /login
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  # only want to create url path for showing users only
  resources :users, only: [:show]
  # no restriction on rooms
  resources :rooms
  # route to photos
  resources :photos
  # route to messages within conversations
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/user.rb
class User < ApplicationRecord

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable

  # Validation for Full Name
  validates :fullname, presence: true, length: {in: 4..50}

  has_many :rooms

  def self.from_omniauth(auth)
    user = User.where(email: auth.info.email).first
    if user
      return user
    else
      # user is not in our database; create a new one
      where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
        user.fullname = auth.info.name
        user.provider = auth.provider
        user.uid = auth.uid
        user.email = auth.info.email
        user.image = auth.info.image
        user.password = Devise.friendly_token[0,20] #create a new password for user
      end
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id])
    @rooms = @user.rooms
  end
end

app/views/users/show.html.erb
<div class="row">

  <div class="col-md-3">
    <div class="center">
      <%= image_tag profile_pic_url(@user), class: "profile-pic-large" %>
      <!-- can't message yourself yo -->
      <% if current_user != @user %>
        <div class="row-space-2">
          <%= link_to "Send Message", conversations_path(sender_id: current_user.id,
          recipient_id: @user.id), method: "post", class: "btn btn-primary wide" %>
        </div>
      <% end %>
    </div>
    <div class="panel panel-default">
      <div class="panel-heading"> Verification</div>
      <div class="panel-body">
        Email Address <br>
        Phone Number
      </div>
    </div>
  </div>

  <div class="col-md-9">
    <h2><%= @user.fullname %></h2>
    <div class="description row-space-3">
      <%= @user.description %>
    </div>
    <h4>Listings (<%= @rooms.length %>)</h4><br>
    <div class="row">
      <% @rooms.each do |room| %>
        <div class="col-md-4">
          <div class="panel panel-default">
            <div class="panel-heading preview">
              <%= image_tag room.photos[0].image.url(:medium) %>
            </div>
            <div class="panel-body">
              <%= link_to room.listing_name, room_path(room) %>
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>