config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for  :users,
              :path => '',
              # shortcut for routs e.g. /users/sign_in = /login
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  # only want to create url path for showing users only
  resources :users, only: [:show]
  # no restriction on rooms
  resources :rooms
  # route to photos
  resources :photos
  # route to messages within conversations
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/views/shared/_devise-msg.html.erb
<!-- the goal of this module is to make the ugly devise
error messages more beautiful - w/ toastr -->
<% unless resource.errors.empty? %>
  <script type="text/javascript">
    <% resource.errors.full_messages.each do |msg| %>
      toastr.error('<%= msg %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_message.html.erb
<!-- Use toastr gem to clean up flash messages -->
<!-- refer to doc: https://github.com/tylergannon/toastr-rails -->
<% unless flash.empty? %>
  <script type="text/javascript">
    <% flash.each do |f| %>
      // replace 'alert' and 'notice' to fit toastr syntax
      <% type = f[0].to_s.gsub('alert', 'error').gsub('notice', 'info') %>
      // message type, message content
      toastr['<%= type %>']('<%= f[1] %>')
    <% end %>
  </script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Bootstrap static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "LivingLAB", root_path, class: "navbar-brand" %>
      <!-- <a class="navbar-brand" href="#">LivingLAB</a> -->
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <!-- navbar changes based on user's status (signed in or nah?) -->
        <% if(!user_signed_in?) %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag profile_pic_url(current_user), class: "img-circle profile-pic-small" %>
              <%= current_user.fullname %>
              <span class="caret"></span>
            </a>
            <ul class="dropdown-menu">
              <li>
                <%= link_to conversations_path do %>
                  <i class="material-icons">message</i> Messages
                <% end %>
              </li>
              <li>
                <%= link_to new_room_path do %>
                  <i class="material-icons">home</i> List Your Home
                <% end %>
              </li>
              <li role="separator" class="divider"></li>
              <li>
                <%= link_to edit_user_registration_path do %>
                  <i class="material-icons">person</i> Edit Profile
                <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <i class="material-icons">exit_to_app</i> Log Out
                <% end %>
              </li>
            </ul>
          </li>
        <% end %>

      </ul>
    </div>
    <!--/.nav-collapse -->
  </div>
</nav>