config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'
  devise_for  :users,
              :path => '',
              # shortcut for routs e.g. /users/sign_in = /login
              :path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
              :controllers => {:omniauth_callbacks => 'omniauth_callbacks'}

  # only want to create url path for showing users only
  resources :users, only: [:show]
  # no restriction on rooms
  resources :rooms
  # route to photos
  resources :photos
  # route to messages within conversations
  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end
end

app/models/room.rb
class Room < ApplicationRecord
  belongs_to :user
  has_many :photos

  # get lat and long w/ address
  geocoded_by :address, :latitude  => :lat, :longitude => :long #ActiveRecord
  after_validation :geocode, if: :address_changed?

  # validate room
  validates :home_type, presence: true
  validates :room_type, presence: true
  validates :accommodate, presence: true
  validates :bedroom, presence: true
  validates :bathroom, presence: true
  validates :listing_name, presence: true, length: {maximum: 50}
  validates :summary, presence: true, length: {maximum: 800}
  validates :address, presence: true
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  # I don't like to repeat code :)
  before_action :set_room, only: [:show, :edit, :update]

  before_action :authenticate_user!, except: [:show]

  def index
    @rooms = current_user.rooms
  end

  def show
    @photos = @room.photos
  end

  def new
    @room = current_user.rooms.build
  end

  def create
    @room = current_user.rooms.build(room_params)
    if @room.save
      # create a photo entity for each image that a room has
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end
      @photos = @room.photos
      redirect_to edit_room_path(@room), notice: "Saved..."
    else
      render :new
    end
  end

  def edit
    # security feature: ensure that editor of home is the owner of that home
    if current_user.id = @room.user.id
      @photos = @room.photos
    else
      redirect_to root_path, notice: "You don't have permission to edit a home you don't own."
    end
  end

  def update
    if @room.update(room_params)
      if params[:images]
        params[:images].each do |image|
          @room.photos.create(image: image)
        end
      end
      redirect_to edit_room_path(@room), notice: "Updated..."
    else
      render :edit
    end
  end

  private
    def set_room
      @room = Room.find(params[:id])
    end

    def room_params
      params.require(:room).permit(:home_type, :room_type, :accommodate,
      :bedroom, :bathroom, :listing_name, :summary, :address, :has_wifi,
      :is_furnished, :has_ac, :has_washer_dryer, :rent, :active)
    end

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/_form.html.erb
<!-- A partial view for room info, used by others -->

<div class="panel panel-default">
  <div class="panel-heading">
    List your home on LivingLAB!
  </div>
  <div class="panel-body">
    <div class="container">
      <%= form_for @room, html: {multipart: true} do |f| %>

        <!-- row for home type, room type, and accommodates -->
        <div class="row">

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Home Type</label>
              <%= f.select :home_type, [["Apartment","Apartment"],["House","House"]],
              id: "home_type", prompt: "Select one", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Room Type</label>
              <%= f.select :room_type, [["Entire","Entire"],["Private","Private"], ["Shared", "Shared"]],
              prompt: "Select one", class: "form-control" %>
            </div>
          </div>

          <div class="col-md-4 select">
            <div class="form-group">
              <label>Accomodates</label>
              <%= f.select :accommodate, [["1","1"],["2","2"],["3","3"],["4","4"],["5","5"],["6+","6+"]],
              prompt: "Select one", class: "form-control" %>
            </div>
          </div>
        </div>

        <!-- row for # of bedrooms and # of bathrooms -->
        <div class="row">
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Number of Bedrooms</label>
              <%= f.select :bedroom, [["1","1"],["2","2"],["3","3"],["4+","4+"]],
              prompt: "Select one", class: "form-control" %>
            </div>
          </div>
          <div class="col-md-4 select">
            <div class="form-group">
              <label>Number of Bathrooms</label>
              <%= f.select :bathroom, [["1","1"],["2","2"],["3","3"],["4+","4+"]],
              prompt: "Select one", class: "form-control" %>
            </div>
          </div>
        </div>

        <!-- row for listing title-->
        <div class="row">
          <div class="form-group">
            <label>Listing Title</label>
            <%= f.text_field :listing_name, placeholder: "Your Listing Title", class: "form-control" %>
          </div>
        </div>

        <!-- row for summary -->
        <div class="row">
          <div class="form-group">
            <label>Summary</label>
            <%= f.text_area :summary, rows:5, placeholder: "Describe your home", class: "form-control" %>
          </div>
        </div>

        <!-- row for address -->
        <div class="row">
          <div class="form-group">
            <label>Address</label>
            <%= f.text_field :address, placeholder: "Enter your home's address", class: "form-control" %>
          </div>
        </div>

        <!-- row for amenities -->
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :has_wifi %> Wifi
            </div>
            <div class="form-group">
              <%= f.check_box :is_furnished %> Furnished
            </div>
          </div>

          <div class="col-md-4">
            <div class="form-group">
              <%= f.check_box :has_ac %> A/C
            </div>
            <div class="form-group">
              <%= f.check_box :has_washer_dryer %> Washer/Dryer
            </div>
          </div>
        </div>

        <!-- row for monthly rent -->
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <label>Monthly Rent</label>
              <div class="input-group">
                <div class="input-group-addon">$</div>
                <%= f.text_field :rent, placeholder: "in USD", class: "form-control" %>
              </div>
            </div>
          </div>
        </div>

        <!-- row for photos -->
        <div class="row">
          <div class="col-md-4">
            <div class="form-group">
              <span class="btn btn-default btn-file">
                <i class="material-icons">cloud_upload</i> Upload Photos
                <%= file_field_tag "images[]", type: :file, multiple: true %>
              </span>
            </div>
          </div>
        </div>

        <div id="photos"><%= render 'photos/list' %></div>

        <!-- row for active -->
        <div class="row">
          <div class="form-group">
            <%= f.check_box :active %> Active
          </div>
        </div>

        <!-- save button -->
        <div class="actions">
          <%= f.submit "Save", class: "btn btn-primary" %>
        </div>

      <% end %>
    </div>
  </div>
</div>

app/views/rooms/create.html.erb
<h1>Rooms#create</h1>
<p>Find me in app/views/rooms/create.html.erb</p>

app/views/rooms/edit.html.erb
<%= render 'form' %>

app/views/rooms/index.html.erb
<div class="row">
  <div class="col-md-3">
    <ul class="sidebar-list">
      <li class="sidebar-item"><%= link_to "Your Listings", rooms_path, class: "sidebar-link active" %></li>
    </ul>
  </div>
  <div class="col-md-9">
    <div class="panel panel-default">
      <div class="panel-heading">
        Your Listings
      </div>
      <div class="panel-body">
        <% @rooms.each do |room| %>
          <div class="row">
            <div class="col-md-2">
              <!-- display the 1st photo of the room, if it has any -->
              <%= image_tag room.photos[0].image.url(:thumb) if room.photos.length > 0 %>
            </div>
            <div class="col-md-7">
              <h4><%= room.listing_name %></h4>
            </div>
            <div class="col-md-3">
              <%= link_to "Update", edit_room_path(room), class: "btn btn-primary" %>
            </div>
          </div>
          <hr>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/rooms/new.html.erb
<%= render 'form' %>

app/views/rooms/show.html.erb
<div class="panel panel-default">
  <div class="panel-body">

    <!-- row for photo -->
    <div class="row">
      <div class="col-md-12">
        <%= image_tag @photos[0].image.url(), class: "img-responsive" if @photos.length > 0 %>
      </div>
    </div>
    <br>

    <!-- Information about the home -->
    <div class="row">
      <div class="col-md-8">

        <div class="col-md-3 text-center">
          <%= image_tag profile_pic_url(@room.user), class: "img-circle profile-pic-large" %>
          <br><br>
          <%= @room.user.fullname %>
        </div>

        <div class="col-md-9">
          <h4><%= @room.listing_name %></h4>
          <%= @room.address %>
          <div class="row text-center row-space-1">
            <div class="col-sm-3">
              <i class="material-icons">home</i>
            </div>
            <div class="col-sm-3">
              <i class="material-icons">people</i>
            </div>
            <div class="col-sm-3">
              <i class="material-icons">local_hotel</i>
            </div>
            <div class="col-sm-3">
              <i class="material-icons">grain</i>
            </div>
          </div>

          <div class="row text-center">
            <div class="col-sm-3">
              <%= @room.home_type %>
            </div>
            <div class="col-sm-3">
              <%= @room.accommodate %>
              <%= @room.accommodate > 1? "LABmates" : "LABmate" %>
            </div>
            <div class="col-sm-3">
              <%= @room.bedroom %>
              <%= @room.bedroom > 1? "Bedrooms" : "Bedroom" %>
            </div>
            <div class="col-sm-3">
              <%= @room.bathroom %>
              <%= @room.bathroom > 1? "Bathrooms" : "Bedroom" %>
            </div>
          </div>
        </div>
      </div>

      <div class="col-md-4">
        <!-- reservation form -->
      </div>
    </div>

    <!-- About -->
    <div class="row">
      <div class="col-md-12">
        <h2>About this Listing</h2>
        <p><%= @room.summary %></p>
      </div>
    </div>

    <!-- Amenities -->
    <div class="row">
      <div class="col-md-2">
        <p>Amenities</p>
      </div>
      <div class="col-md-10">
        <div class="row">
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'strike-through' if !@room.has_wifi %>">Wifi Included</li>
              <li class="<%= 'strike-through' if !@room.is_furnished %>">Fully Furnished</li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="amenities">
              <li class="<%= 'strike-through' if !@room.has_ac %>">Air Conditioning</li>
              <li class="<%= 'strike-through' if !@room.has_washer_dryer %>">Washer/Dryer</li>
            </ul>
          </div>
        </div>
      </div>
    </div>

    <!-- Photo Carousel -->
    <div class="row">
      <div class="col-md-10 col-md-offset-1">
        <!-- Bootstrap Carousel -->
        <div id="myCarousel" class="carousel slide" data-ride="carousel">

          <% if @photos %>
            <!-- Indicators -->
            <ol class="carousel-indicators">
              <% @photos.each do |photo| %>
                <li data-target="#myCarousel" data-slide-to="<%= photo.id %>"></li>
              <% end %>
            </ol>
          <% end %>

          <!-- Wrapper for slides -->
          <div class="carousel-inner">
            <% if @photos %>
              <% @photos.each do |photo| %>
                <!-- Apply active class only if the photo displayed is the first photo -->
                <div class="item <%= 'active' if photo.id == @photos[0].id %>">
                  <%= image_tag photo.image.url() %>
                </div>
              <% end %>
            <% end %>
          </div>

          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
      </div>
    </div>

    <br>
    <hr>

    <!-- Google Maps Integration -->
    <div class="row">
      <div class="col-md-12">
        <div id="map"></div>
        <style>
          #map {
            height: 400px;
            width: 100%;
           }
        </style>
        <script>
          function initMap() {
            var uluru = {lat: <%= @room.lat %>, lng: <%= @room.long %>};
            var map = new google.maps.Map(document.getElementById('map'), {
              zoom: 14,
              center: uluru
            });
            var marker = new google.maps.Marker({
              position: uluru,
              map: map
            });
          }
        </script>
        <script async defer
        src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAjerE7aE54Iu4JbyaBVWqVGbM0_Tek3bY&callback=initMap">
        </script>

      </div>
    </div>



  </div>
</div>

app/views/rooms/update.html.erb
<h1>Rooms#update</h1>
<p>Find me in app/views/rooms/update.html.erb</p>